#!/bin/bash
#~~~~~~~~~~
# Generated by cmake from simply-cpp's scripts/run.sh.in.
# Edit the template, not this copy: sc_bootstrap.cmake reports when this file has
# drifted, and -DSC_UPDATE_HELPERS=ON puts it back.
#
# Runs on the server, in the directory deploy.sh synced to.

module="sc-db"
version=""
ubuntu_codename=$(lsb_release -sc)
build_directory="cmake-build-$ubuntu_codename"
apt -y install cmake clang-tidy ccache g++

pushd "/var/www/build/$module" || exit

if [ -f scripts/pre-build.sh ]; then
    echo "Running pre-build"
    ./scripts/pre-build.sh
else
    echo "No pre-build required"
fi

configure_and_build() {
    cmake -DCMAKE_BUILD_TYPE=Release -B "$build_directory" -S . && \
    cmake --build "$build_directory" -j 12
}

# /var/www/build is shared across all build-* servers, and $build_directory is
# reused between deploys - if this host's toolchain/deps changed since it was
# last configured here, the cache can go stale and hide the real state (e.g.
# find_package() trusting a cached result instead of re-checking). One clean
# retry recovers from that without needing to debug it by hand each time.
if ! configure_and_build; then
    echo "Build failed - cleaning $build_directory and retrying once in case its cache is stale for this host."
    rm -rf "$build_directory"
    configure_and_build || exit
fi

ctest --test-dir $build_directory --output-on-failure || exit
cmake --install $build_directory

pushd $build_directory || exit
rm -rf *.deb
cpack --config CPackConfig.cmake -G DEB
rm -rf *unknown*.deb
rsync -av *.deb /var/www/build/debs/
rm -rf /var/www/build/debs/*unknown*
popd || exit

debfile="${module/sc-/simply-cpp-}"
debfile="${debfile/-cpp-core/-cpp}"
echo "Updating repository $debfile $version"
pushd /var/www/build/repo || exit
export GNUPGHOME=/var/www/build/signing
reprepro remove $ubuntu_codename $debfile
reprepro remove $ubuntu_codename $debfile-dev
reprepro list $ubuntu_codename
for deb in ../debs/*.deb; do
    [ -f "$deb" ] || continue
    echo "Loading $deb"
    reprepro includedeb $ubuntu_codename "$deb"
    mv "$deb" ../debs/processed/
done
reprepro list $ubuntu_codename
popd || exit

popd || exit
